version = 0.1
[default.deploy.parameters]
stack_name = "unicorn-birth-app"
resolve_s3 = true
s3_prefix = "unicorn-birth-app"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
